export const metadata = {
    title: ' About Mounika padala',
    description: 'Generated by mounika padala',
    keywords:'passive income, small bets'
  }
const AboutPage=()=>{
    return(
        <div>
            About Page
        </div>
    );
}
export default AboutPage;